service: email-python
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  hello:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: /
          method: post

